language: bash

os:
- linux

env:
  - BASHVER=
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4

matrix:
  include:
    - os: osx

services:
  - docker

script:
- |
  if [[ "$TRAVIS_OS_NAME" == 'linux' && -n "$BASHVER" ]]; then
    docker build --build-arg bashver=${BASHVER} --tag adoyle/lobash:bash-${BASHVER} .
    docker run -it bash:${BASHVER} --version
    time docker run -it adoyle/lobash:bash-${BASHVER} /opt/lobash/run_test
  else
    time run_test
  fi

notifications:
  email:
    on_success: never
