language: bash

git:
  depth: 1
  submodules: false

branches:
  only:
    - master
    - test

services:
  - docker

os:
  - linux
  - osx

env:
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4
  - BASHVER=5.0

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == 'linux' ]; then
      sudo apt-get update
      sudo apt-get install -y bash=4
    else
      brew install bash@4
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      docker pull lobash/test-bash:${BASHVER}
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      time ./tools/test-in-docker
    else
      bash --version
      time run_test
    fi

notifications:
  email:
    on_success: never
