language: bash

git:
  depth: 1
  submodules: false

branches:
  only:
    - master
    - test

services:
  - docker

os:
  - linux
  - osx

env:
  - BASHVER=4.4
  - BASHVER=5.0
  - ZSHVER=5.3
  - ZSHVER=5.4
  - ZSHVER=5.5
  - ZSHVER=5.6
  - ZSHVER=5.7

cache:
  directories:
    - $TRAVIS_BUILD_DIR/build-bash

install:
  - |
    # Default Travis CI use Bash 4.3 in Linux, and 3.2 in MacOS.
    # Out script use shopt -s inherit_errexit but only Bash 4.4+ supported.
    if [[ -x $TRAVIS_BUILD_DIR/build-bash/bin/bash ]]; then
      echo "Use cache: build-bash"
    else
      echo "No cache, to install and build Bash ${BASHVER}"
      ./tools/install-bash ${BASHVER} 2>&1 >> build.log || cat build.log
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
      git submodule update --init --depth 1
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      if [[ -n ${ZSHVER:-} ]]; then
        docker pull lobash/test-zsh:${ZSHVER}
      else
        docker pull lobash/test-bash:${BASHVER}
      fi
    fi

script:
  - export PATH="$TRAVIS_BUILD_DIR/build-bash/bin:$PATH"
  - printf "%s\n%s\n" "The Bash used for test:" "$(bash --version)"
  - |
    if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      if [[ -n ${ZSHVER:-} ]]; then
        # Start to test in Zsh docker
        time bash ./tools/test-zsh-in-docker
      else
        # Start to test in Bash docker
        time bash ./tools/test-bash-in-docker
      fi
    else
      # Start to test in MacOS
      time bash ./test
    fi

notifications:
  email:
    on_success: never
